repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.8
    hooks:
      # Run the linter.
    -   id: ruff
        # Avoiding running on Jupyter Notebooks, fix linting issues
        #types_or: [ python, pyi ]
        args: [ "--fix" ]
        stages: [pre-commit]
      # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi ]
        stages: [pre-commit]
